### ISSUE TITLE
Here is a list of Xamarin.Forms apps

### ISSUE THREAD

**Issue by sturlath** [jsuarezruiz/xamarin-forms-goodlooking-UI#1]
More Xamarin.Forms apps https://gist.github.com/davidortinau/5c9129e2bfaabafcb58df07325cb4a90

Its currated by David Ortinau https://github.com/davidortinau

**Comment by jsuarezruiz** [comment]
This list is great. Great compilation by David. We will add the reference to this listing from here!.
