### ISSUE TITLE
UI entry from Snppts

### ISSUE THREAD

**Issue by devoirtechsandip** [jsuarezruiz/xamarin-forms-goodlooking-UI#11]
I have submitted snppts entry under snpptschallenge. If it is worth consideration to be included alongside with legends such as Kym Phillpotts, Steven Thewissen.

Project source: https://github.com/devoirtechsandip/SnpptsChallenge

Thanks,
Sandip Kumbhar

**Comment by jsuarezruiz** [comment]
Sure thing, just send a PR. I am going to close the issue for now but let me know if you need help with something.
