### ISSUE TITLE
Converting to .NET MAUI !

### ISSUE THREAD

**Issue by SaddamBInSyed** [jsuarezruiz/xamarin-forms-goodlooking-UI#21]
HI, thanks for the great repo.

I am a newbie to .NET MAUI, I would like to see these repo applications in .NET MAUI also.
So a beginner like me can play around the things with good UI.

thanks

**Comment by IeuanWalker** [comment]
@SaddamBInSyed 
Just you are aware this repo just links to other people's repos in the community, so they may not all be updated to MAUI. But you could look at those specific repos, and raise an issue with them to see if they are planning to migrate them

There is a new repo though, specific to MAUI apps - https://github.com/jsuarezruiz/net-maui-goodlooking-UI

A lot of the stuff in the xamarin projects will more than likely just work in a MAUI app though, so this repo is still useful.

**Comment by SaddamBInSyed** [comment]
@IeuanWalker @jsuarezruiz 

Thank you for your response.

I will try to reuse these(  UI )xamarin apps in Maui projects. 

If possible could you please share some guide  about converting xamarin apps to Maui projects ( mainly the UI part )

So this will definitely help newbie like me to proceed.

Thanks

**Comment by IeuanWalker** [comment]
@SaddamBInSyed no prob.

From my experience they should be the same, so the xaml in a xamarin project should map directly to maui xaml.

Its mostly internal stuff that have changed between xamarin and maui

**Comment by SaddamBInSyed** [comment]
@IeuanWalker @jsuarezruiz 

I have posted my issue [here](https://github.com/dotnet/maui/issues/8249#issue-1280774086). Could you please advise me what I am doing wrong here?

help is highly appreciated.
