### ISSUE TITLE
New Xamarin UI templates

### ISSUE THREAD

**Issue by prabakaranr** [jsuarezruiz/xamarin-forms-goodlooking-UI#8]
Hi @jsuarezruiz 

Here you do a fantastic job. This builds trust for developers who want to work with Xamarin.Forms and also contributes to learning the source code of the required UI project.

I think adding Essential UI Kit for Xamarin.Forms to this list will add some more benefits. There are over 35 XAML UIs that work with Android, iOS and UWP platforms. Please check the link below for more information.

https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms

I'm happy to create a new pull request with Essential UI Kit if you wish.

Thanks,
Prabakaran

**Comment by jsuarezruiz** [comment]
Thanks!. I have added "Essential UI Kit for Xamarin.Forms" to the list. Nice work.

**Comment by prabakaranr** [comment]
Thank you very much!.
